# IP address and port of your receiver
receiver:
  address: "192.168.1.180"
  port: 60128

# Port the web service listens on
http_port: 8080

# Enable the javascript-based remote app
web_remote: true

# Debugging tools, enables the /api/xml and /api/raw/:command endpoints
# You should leave this disabled unless you explicitly need this functionality.
debug_tools: false

# Max volume you can set using onkyo-remote
max_volume: 40

# Logging settings
logging:
  eiscp: false
  http: false
