# IP address and port of your receiver
receiver:
  address: "192.168.1.180"
  port: 60128

# Port the web service listens on
http_port: 8080

# Enable the javascript-based remote app
web_remote: true

# Enable or disable the /api/raw/:command endpoint
api_raw: false

# Max volume you can set using onkyo-remote
max_volume: 40

# Logging settings
logging:
  eiscp: true
  http: true

# Input declarations
# Only inputs specified here will be renamed from their defaults
inputs:
  - hex: 20
    name: "TV Optical Out"
  - hex: 02
    name: "PolyStation 2"
